### ISSUE TITLE
[BUG]: The vhp.burn method is misnamed

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-contracts-as#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The method named `burn()` has the semantics of "Destroy the VHP with a side effect of creating an equal amount of KOIN."

### Expected behavior

As a user, I expect the semantics of a method named `vhp.burn()` should be "Destroy the VHP with no side effects."

### Environment

```markdown
- OS: All
```

### Anything else?

Suggested fix:

- Rename the method currently named `vhp.burn()` to `vhp.convert_to_koin()`.
- Implement a new method named `vhp.burn()` whose functionality is "Destroy the VHP with no side effects."

KOIN version of this bug: https://github.com/koinos/koinos-contracts-cpp/issues/78

**Comment by sgerbino** [comment]
The `vhp.burn` method already destroys VHP with no side effects.
