### ISSUE TITLE
[QUESTION]: What is the purpose of name service?

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-contracts-as#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the documentation?

- [X] I have read the documentation

### Ask a question

According to an article [here](https://medium.com/koinosnetwork) the name service is supposed to be an ENS substitute and dApp developers.  The article implies that users will be able to register names.

However the contract seems to be written as if it's intended to only be invoked by governance:

- It [requires system authority](https://github.com/koinos/koinos-contracts-as/blob/5f10731d3442f21d633e12f098cfa82606f3722b/contracts/name_service/assembly/NameService.ts#L26)
- The state objects (`name_record` / `address_record`) don't contain any information about who is allowed to update the record
- Input accepts any string (if accessible to users it should be e.g. restricted to ASCII, to prevent [homograph attack](https://en.wikipedia.org/wiki/IDN_homograph_attack) )
- Names are free
- There are no anti-spam measures

So here are my questions:

- If there's no self-service, and governance action is required to approve a new name, is it really a substitute for ENS?
- If there is self-service, what prevents one person from registering every name in the dictionary as fast as their mana will allow?
- In what situations would a contract need to reference a system contract by ID?  Wouldn't the system contracts instead be referenced by [system call ID](https://github.com/koinos/koinos-proto/blob/863dd26dd505b08613214a9e19a5a32f44722723/koinos/chain/system_call_ids.proto)?
- If mainnet launches with all names requiring governance to update, and self-service may be a future update, perhaps the names used by the system and updateable by governance should be prefixed (e.g. `sys.whatever`) so that when/if that future update releases, system names don't get confused with user-controlled names?

### Anything else?

To answer my own question:

> In what situations would a contract need to reference a system contract by ID?

One big example is the KOIN contract.  If you want to transfer KOIN you need to know the address of the KOIN contract.

Let's sketch out the hypothetical case for an on-chain name service a little further:  Suppose there's some future feature update that requires updating the KOIN contract.  If that update changes the address of the KOIN contract, you need a dynamic mapping.  I.e., every contract that references KOIN will only be correct if it asks the name service for the address of the KOIN contract.

However, the previous paragraph contains a pretty big assumption:

> If that update changes the address of the KOIN contract

And this assumption is definitely false.  Since Koinos smart contracts are upgradeable, the update would occur in-place.  That is, the new contract would have the same address as the old contract.

There's also a big benefit to hard-coding the address instead of using name lookup:  It saves one state lookup worth of gas.

To recap:

- User contracts do need to access some system contracts (e.g. KOIN) directly (not via system calls).
- In my view, it's fine if users hard-code the address of such contract(s).
- Even if you disagree with my view, and recommend user contracts shouldn't hardcode addresses of system contracts, some users coming from Ethereum or other ecosystems will probably not get the message and do it anyway.
- As long as *some* user contracts hard-code the address of KOIN, governance *really can't* change the address of the KOIN contract without breaking the world.
- Therefore, a properly designed update *must* put the new functionality in the same contract address.
- Since we've now proven the KOIN contract must keep the same address forever, there's no need for a dynamic lookup.
- Dynamic lookup spends extra gas for no purpose.

Having a name service is still useful for certain kinds of generic tooling, but it seems like two anti-patterns to be avoided are:

- Doing name-based dynamic lookup of contract addresses for system contracts
- Deploying updates that change the address of system contracts

**Comment by theoreticalbts** [comment]
One thing that occurred to me is that the name service may be inspired by a pain point:  Contracts may have different addresses on testnet vs. mainnet.

The simplest workaround for this pain point is to have the same private key upload contracts on testnet and mainnet; that way they end up at the same address.  When uploading a system contract, the authority to update the code should be assigned away from the private key to governance (see #52 ), preferably in the same transaction when the contract is uploaded.

**Comment by mvandeberg** [comment]
It has to do with if we need to update a system contract without an associated system call. A simple solution would be to have the system contract set its upload authority to the system and then rely on the governance contract to handle the proposed upload. And the governance contract can handle this in theory. But the compute cost of allocating such a large buffer makes the contract nearly unusable. We've decided to keep the buffer small and arbitrarily restrict governance proposals to setting system calls and system contracts.

So, when we want to update the KOIN contract, for example, we upload a new contract and in a proposal make the necessary changes for the new contract to serve as the KOIN contract. This means there is a different address. This causes problems for system contracts and user contracts that rely on the KOIN contract being at a particular address. This name service is a system only service for allowing user and system contracts to look up system contracts by name, preventing them from needing to upgrade if such a system update needs to be made in the future.
